-- Esquema de Luciérnaga en PostgreSQL (Supabase).
--
-- Generado por backend/scripts/migracion/generar-esquema-pg.cjs a partir del
-- esquema real de MySQL, no de database/schema.sql, que ya no refleja lo que
-- hay en la base.
--
-- Diferencias respecto a MySQL, todas deliberadas:
--
--   * AUTO_INCREMENT pasa a GENERATED BY DEFAULT AS IDENTITY, que admite que la
--     migración inserte los ids existentes. Al final se recolocan las secuencias.
--   * ON UPDATE CURRENT_TIMESTAMP no existe en PostgreSQL: se sustituye por el
--     trigger `tocar_updated_at`, definido abajo una sola vez.
--   * Los enum de MySQL pasan a varchar con un CHECK: un enum de PostgreSQL es
--     un tipo propio y obligaría a migrarlo aparte sin ganar nada aquí.
--   * Las columnas de `inventario` van entre comillas porque están en
--     mayúsculas; sin comillas, PostgreSQL las pasaría a minúsculas.
--
-- Idempotente: se puede ejecutar varias veces.
--
-- El perfil CALIDAD se retiró del software: sus tablas (`asignacion_caja_calidad`,
-- `asignacion_calidad`, `modulo_calidad`) ya no se crean. En una base que las
-- tenga, `04-sin-calidad.sql` las retira.


CREATE TABLE IF NOT EXISTS asignacion_caja_tecnica (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  modulo_id integer NOT NULL,
  usuario_id integer NOT NULL,
  upd_inicio varchar(10),
  ultimo_upd varchar(10),
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS asignacion_caja_tecnica_modulo_id ON asignacion_caja_tecnica (modulo_id);
CREATE INDEX IF NOT EXISTS asignacion_caja_tecnica_usuario_id ON asignacion_caja_tecnica (usuario_id);

-- Cierre de jornada declarado por quien digita: "esta caja la terminé" o "la
-- sigo mañana". Lo demás de una jornada (cuántos registros, a qué hora, con qué
-- UPD) se deduce de fuiddatosreal; la intención no se puede deducir, y es lo
-- que permite dar por cerrada la producción de un día aunque la caja siga
-- abierta al siguiente. Una fila por caja, día y persona.
CREATE TABLE IF NOT EXISTS jornada_caja (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  caja_modulo varchar(255) NOT NULL,
  fecha date NOT NULL,
  colaborador varchar(255) NOT NULL,
  resultado varchar(20) NOT NULL,
  usuario_id integer,
  registros integer,
  declarada_en timestamp DEFAULT now(),
  PRIMARY KEY (id),
  CONSTRAINT uq_jornada_caja UNIQUE (caja_modulo, fecha, colaborador),
  CONSTRAINT jornada_caja_resultado CHECK (resultado IN ('TERMINADA', 'CONTINUA'))
);

CREATE INDEX IF NOT EXISTS idx_jornada_caja_caja ON jornada_caja (caja_modulo);

CREATE TABLE IF NOT EXISTS asignacion_tecnica (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  modulo_id integer NOT NULL,
  usuario_id integer NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS asignacion_tecnica_modulo_id ON asignacion_tecnica (modulo_id);
CREATE INDEX IF NOT EXISTS asignacion_tecnica_usuario_id ON asignacion_tecnica (usuario_id);

CREATE TABLE IF NOT EXISTS auditoria (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  entidad varchar(100) NOT NULL,
  entidad_id varchar(100),
  accion varchar(30) NOT NULL,
  detalle varchar(500),
  usuario varchar(150),
  fecha timestamp DEFAULT now() NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS auditoria_idx_auditoria_entidad ON auditoria (entidad, entidad_id);
CREATE INDEX IF NOT EXISTS auditoria_idx_auditoria_fecha ON auditoria (fecha);

CREATE TABLE IF NOT EXISTS fuiddatosreal (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  fecha_del_dato date,
  n_orden integer,
  codigo varchar(255),
  entidad_remitente varchar(255),
  entidad_productora varchar(255),
  unidad_administrativa varchar(255),
  oficina_productora varchar(255),
  objeto varchar(255),
  serie varchar(255),
  subserie varchar(255),
  numero_de_orden_interno varchar(255),
  accionado_procesado varchar(255),
  accionado_denunciante varchar(255),
  identificacion varchar(255),
  asunto varchar(255),
  radicado varchar(255),
  numero_doc varchar(255),
  numero_doc_hasta varchar(255),
  fecha_inicial date,
  fecha_final date,
  caja varchar(255),
  upd varchar(255),
  tomo varchar(255),
  otro varchar(255),
  caja_interna varchar(255),
  folios varchar(255),
  soporte varchar(255),
  frecuencia varchar(255),
  elaborado_por varchar(255),
  nro_acta_transferible varchar(255),
  fecha_transferencia date,
  notas varchar(255),
  sede varchar(255),
  tiempo time,
  historial_y_cambios text,
  cambio_calidad varchar(255),
  sede_calidad varchar(255),
  asunto_2 varchar(255),
  asunto_3 varchar(255),
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now(),
  version integer DEFAULT 1 NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_upd UNIQUE (upd)
);

CREATE INDEX IF NOT EXISTS fuiddatosreal_idx_fuid_acta ON fuiddatosreal (nro_acta_transferible);
CREATE INDEX IF NOT EXISTS fuiddatosreal_idx_fuid_elaborado_por ON fuiddatosreal (elaborado_por);
CREATE INDEX IF NOT EXISTS fuiddatosreal_idx_fuid_estado_revision ON fuiddatosreal (historial_y_cambios);
CREATE INDEX IF NOT EXISTS fuiddatosreal_idx_fuid_fecha_dato ON fuiddatosreal (fecha_del_dato);
CREATE INDEX IF NOT EXISTS fuiddatosreal_idx_fuid_sede ON fuiddatosreal (sede);
CREATE INDEX IF NOT EXISTS fuiddatosreal_idx_fuiddatosreal_caja ON fuiddatosreal (caja);

CREATE TABLE IF NOT EXISTS historial (
  id_historial integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_dato integer NOT NULL,
  fecha_del_dato date,
  n_orden integer,
  codigo varchar(255),
  entidad_remitente varchar(255),
  entidad_productora varchar(255),
  unidad_administrativa varchar(255),
  oficina_productora varchar(255),
  objeto varchar(255),
  serie varchar(255),
  subserie varchar(255),
  asunto varchar(255),
  radicado varchar(255),
  numero_doc varchar(255),
  numero_doc_hasta varchar(255),
  fecha_inicial date,
  fecha_final date,
  caja varchar(255),
  upd varchar(255),
  tomo varchar(255),
  otro varchar(255),
  caja_interna varchar(255),
  folios varchar(255),
  soporte varchar(255),
  frecuencia varchar(255),
  elaborado_por varchar(255),
  nro_acta_transferible varchar(255),
  fecha_transferencia date,
  notas varchar(255),
  sede varchar(255),
  tipo_cambio varchar(20),
  fecha_cambio timestamp DEFAULT now(),
  tiempo time,
  historial_cambios varchar(255),
  cambio_calidad varchar(255),
  sede_calidad varchar(255),
  PRIMARY KEY (id_historial)
);

CREATE INDEX IF NOT EXISTS historial_idx_historial_fecha_cambio ON historial (fecha_cambio);
CREATE INDEX IF NOT EXISTS historial_idx_historial_sede_calidad ON historial (sede_calidad);
CREATE INDEX IF NOT EXISTS historial_idx_historial_tipo_cambio ON historial (tipo_cambio);

CREATE TABLE IF NOT EXISTS inventario (
  "ITEMS" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "CODIGO_DEL_CLIENTE" varchar(255),
  "CLIENTE" varchar(255),
  "No_ACTA" varchar(255),
  "FECHA_TRANSFERENCIA" date,
  "X200" integer,
  "X300" integer,
  "X400" integer,
  "NC" integer,
  "TOTAL_CAJAS" integer,
  "ANEXOS" varchar(255),
  "FECHA_ENTREGA_CUSTODIA" date,
  "FUNCIONARIO" varchar(255),
  "ESTADO_DEL_INVENTARIO" varchar(255),
  "CAJAS_PROCESADAS" integer,
  "CAJA_INICIAR" varchar(255),
  "CAJ_FIN" varchar(255),
  "REGISTROS_PROCESADOS" integer,
  "FECHA_ENTREGA" date,
  "INICIO_INVENTARIO" date,
  "FIN_INVENTARIO" date,
  "ESTADO_ENTREGA" varchar(255),
  "MES_ENTREGA_PACA" varchar(255),
  "FECHA_CREACION" timestamp DEFAULT now(),
  "FECHA_ACTUALIZACION" timestamp DEFAULT now(),
  "USUARIO_ACTUALIZACION" varchar(150),
  "ZOHO_FILE_ID" varchar(500),
  "ZOHO_SYNC_STATE" varchar(20),
  "ZOHO_SYNC_AT" timestamp,
  "ZOHO_SYNC_ERROR" text,
  PRIMARY KEY ("ITEMS")
);

CREATE TABLE IF NOT EXISTS modulo_tecnica (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  modulo_id integer NOT NULL,
  usuario_id integer NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS modulo_tecnica_modulo_id ON modulo_tecnica (modulo_id);
CREATE INDEX IF NOT EXISTS modulo_tecnica_usuario_id ON modulo_tecnica (usuario_id);

CREATE TABLE IF NOT EXISTS modulos_caja (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  caja_modulo varchar(255) NOT NULL,
  entidad_remitente_caja varchar(255) NOT NULL,
  acta_trans_caja varchar(255) NOT NULL,
  fecha_trans_caja date NOT NULL,
  id_modulo_caja integer,
  entidad_productora_caja varchar(255),
  unidad_administrativa_caja varchar(255),
  oficina_productora_caja varchar(255),
  objeto_caja varchar(255),
  estado_caja varchar(255),
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now(),
  PRIMARY KEY (id),
  CONSTRAINT uq_modulos_caja_caja_modulo UNIQUE (caja_modulo)
);

CREATE INDEX IF NOT EXISTS modulos_caja_id_modulo_caja ON modulos_caja (id_modulo_caja);
CREATE INDEX IF NOT EXISTS modulos_caja_idx_modulos_caja_caja_modulo ON modulos_caja (caja_modulo);
CREATE INDEX IF NOT EXISTS modulos_caja_idx_modulos_caja_estado ON modulos_caja (estado_caja);
CREATE INDEX IF NOT EXISTS modulos_caja_idx_modulos_caja_id_modulo ON modulos_caja (id_modulo_caja);

CREATE TABLE IF NOT EXISTS moduloscliente (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo varchar(255),
  entidad_remitente varchar(255),
  acta_transferencia_modulo varchar(255),
  fecha_trans_modulo date,
  id_submodulo integer,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now(),
  upd_siguiente varchar(10),
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS moduloscliente_fk_submodulo ON moduloscliente (id_submodulo);
CREATE INDEX IF NOT EXISTS moduloscliente_idx_moduloscliente_codigo ON moduloscliente (codigo);
CREATE INDEX IF NOT EXISTS moduloscliente_idx_moduloscliente_submodulo ON moduloscliente (id_submodulo);

CREATE TABLE IF NOT EXISTS rangos_upd (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  usuario_id integer NOT NULL,
  sub_modulo_id integer NOT NULL,
  upd_inicio varchar(10) NOT NULL,
  upd_fin varchar(10) NOT NULL,
  estado varchar(8) DEFAULT 'activo' NOT NULL CHECK (estado IN ('activo', 'agotado', 'revocado')),
  asignado_por integer NOT NULL,
  fecha_asignacion timestamp DEFAULT now() NOT NULL,
  fecha_agotado timestamp,
  fecha_revocacion timestamp,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS rangos_upd_idx_rangos_asignado_por ON rangos_upd (asignado_por);
CREATE INDEX IF NOT EXISTS rangos_upd_idx_rangos_usuario_sub ON rangos_upd (usuario_id, sub_modulo_id, estado);

CREATE TABLE IF NOT EXISTS sub_modulos (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo varchar(255) NOT NULL,
  entidad_remitente varchar(255) NOT NULL,
  sede_submodulos varchar(255),
  PRIMARY KEY (id)
);


-- El código de un cliente es único dentro de su sede: es lo que identifica al
-- cliente en el número de caja y en los reportes, y dos iguales en la misma
-- sede mezclarían sus cajas sin forma de separarlas. Entre sedes sí se repite.
CREATE UNIQUE INDEX IF NOT EXISTS uq_sub_modulos_codigo_sede
  ON sub_modulos (codigo, sede_submodulos);

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  cc varchar(50) NOT NULL,
  nombre varchar(100) NOT NULL,
  contrasena varchar(60),
  rol varchar(50) NOT NULL,
  sede varchar(255),
  suspendido_hasta date,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now(),
  PRIMARY KEY (id)
);

-- Llaves foráneas
ALTER TABLE asignacion_caja_tecnica ADD CONSTRAINT asignacion_caja_tecnica_ibfk_1 FOREIGN KEY (modulo_id) REFERENCES modulos_caja (id) ON DELETE CASCADE;
ALTER TABLE asignacion_caja_tecnica ADD CONSTRAINT asignacion_caja_tecnica_ibfk_2 FOREIGN KEY (usuario_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE asignacion_tecnica ADD CONSTRAINT asignacion_tecnica_ibfk_1 FOREIGN KEY (modulo_id) REFERENCES sub_modulos (id) ON DELETE CASCADE;
ALTER TABLE asignacion_tecnica ADD CONSTRAINT asignacion_tecnica_ibfk_2 FOREIGN KEY (usuario_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE modulo_tecnica ADD CONSTRAINT modulo_tecnica_ibfk_1 FOREIGN KEY (modulo_id) REFERENCES moduloscliente (id) ON DELETE CASCADE;
ALTER TABLE modulo_tecnica ADD CONSTRAINT modulo_tecnica_ibfk_2 FOREIGN KEY (usuario_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE modulos_caja ADD CONSTRAINT modulos_caja_ibfk_1 FOREIGN KEY (id_modulo_caja) REFERENCES moduloscliente (id);
ALTER TABLE moduloscliente ADD CONSTRAINT fk_submodulo FOREIGN KEY (id_submodulo) REFERENCES sub_modulos (id);

-- Equivalente de ON UPDATE CURRENT_TIMESTAMP.
CREATE OR REPLACE FUNCTION tocar_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS fuiddatosreal_updated_at ON fuiddatosreal;
CREATE TRIGGER fuiddatosreal_updated_at BEFORE UPDATE ON fuiddatosreal
  FOR EACH ROW EXECUTE FUNCTION tocar_updated_at();

DROP TRIGGER IF EXISTS modulos_caja_updated_at ON modulos_caja;
CREATE TRIGGER modulos_caja_updated_at BEFORE UPDATE ON modulos_caja
  FOR EACH ROW EXECUTE FUNCTION tocar_updated_at();

DROP TRIGGER IF EXISTS moduloscliente_updated_at ON moduloscliente;
CREATE TRIGGER moduloscliente_updated_at BEFORE UPDATE ON moduloscliente
  FOR EACH ROW EXECUTE FUNCTION tocar_updated_at();

DROP TRIGGER IF EXISTS users_updated_at ON users;
CREATE TRIGGER users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION tocar_updated_at();
