-- Reapertura de cajas por solicitud, y los avisos con los que se entera cada
-- quien.
--
-- La técnica ya no reabre una caja terminada por su cuenta: ni cambiando el
-- estado ni digitando en ella. Lo pide desde el software, el líder de la sede
-- recibe el aviso al instante, lo aprueba o lo rechaza, y la técnica recibe a
-- su vez el aviso de que la caja ya está disponible. Como ninguna caja se
-- cierra sola, este caso aparece solo cuando la técnica o el líder la dieron
-- por terminada y hace falta volver a ella.
--
-- `solicitud_reapertura` es cada petición, con quién la hizo, sobre qué caja,
-- en qué sede estaba la caja (que es lo que decide qué líderes la ven) y cómo
-- se resolvió. El índice único parcial es lo que impide dos solicitudes
-- pendientes de la misma persona sobre la misma caja: volver a pulsar
-- devuelve la que ya está.
--
-- `notificacion` es cada aviso para cada persona, con la caja y la solicitud
-- a las que se refiere, para que desde el aviso se pueda ir a la caja o
-- aprobar la solicitud. Se conserva leída o no: la campana muestra las
-- últimas y cuenta las que quedan sin leer.
--
-- La entrega inmediata no está aquí: la hace el servidor por una conexión
-- abierta con cada pestaña (`backend/src/services/notificaciones.service.ts`).
-- Estas tablas son lo que hace que nada se pierda si la persona no estaba
-- conectada en ese momento.
--
-- Idempotente. El servidor lo aplica también al arrancar
-- (`backend/src/config/esquema.ts`); este archivo existe para poder hacerlo a
-- mano sobre una base nueva.

CREATE TABLE IF NOT EXISTS solicitud_reapertura (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  caja_id integer NOT NULL,
  caja_modulo varchar(255) NOT NULL,
  solicitante_id integer NOT NULL,
  solicitante varchar(255) NOT NULL,
  sede varchar(255),
  estado varchar(20) NOT NULL DEFAULT 'PENDIENTE',
  creada_en timestamp NOT NULL DEFAULT now(),
  resuelta_en timestamp,
  resuelta_por varchar(255),
  resuelta_por_id integer,
  PRIMARY KEY (id),
  CONSTRAINT solicitud_reapertura_estado CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_solicitud_reapertura_pendiente
  ON solicitud_reapertura (caja_id, solicitante_id) WHERE estado = 'PENDIENTE';
CREATE INDEX IF NOT EXISTS idx_solicitud_reapertura_caja ON solicitud_reapertura (caja_id);
CREATE INDEX IF NOT EXISTS idx_solicitud_reapertura_solicitante ON solicitud_reapertura (solicitante_id);

CREATE TABLE IF NOT EXISTS notificacion (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  usuario_id integer NOT NULL,
  tipo varchar(40) NOT NULL,
  mensaje varchar(500) NOT NULL,
  caja_id integer,
  caja_modulo varchar(255),
  solicitud_id integer,
  creada_en timestamp NOT NULL DEFAULT now(),
  leida_en timestamp,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_notificacion_usuario ON notificacion (usuario_id, leida_en);
